# This is an example query for subclass/superclass relations in the dataset

PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?sub ?super

WHERE {
	?sub rdfs:subClassOf ?super .
	FILTER ( ?sub != ?super )
	FILTER ( isIRI(?super) )
}

ORDER BY ?sub
